#!/usr/bin/env bash

# Ich schreibe jetzt ein Programm, welches probiert Programm direkt Startklar
# zu machen, also touch, chmod und dann vim startet (wenn das geht)

function fehler() {
    echo "Fehler bei der Eingabe:"
    echo "tmod <file_name> <chmod>"
    echo "or use tmod -h for help"
}

var_name="$1"
var_chmod="$2"
var_vim="$3"

if [[ -n "${var_name}" && "${var_chmod}" =~ ^[0-9]{3}$ ]]; then
    touch "${var_name}"
    #echo "${var_name} is touched"
    chmod "${var_chmod}" "${var_name}"
    #echo "${var_name} has changed its mod to ${var_chmod}"

    if [[ "${var_vim}" == "vim" || "${var_vim}" == "v" ]]; then
        vim "${var_name}"
    else
        echo -e  "\033[1;32m                _  _\033[0m"
        echo -e  "\033[1;32m[--|--]|\    /|/ \| \ \033[0m"
        echo -e  "\033[1;32m   |   | \  / |   |  | \033[0m"
        echo -e  "\033[1;32m   |   |  \/  |\_/|_/ \033[0m"
        echo -e  "\033[1;34m------------------------------------"
        echo -e  "\033[1;34mDie Datei ${var_name} wurde angelegt "
        echo -e  "\033[1;34m------------------------------------"
	echo -e "\033[1;37m\033[0m"
    fi
else
    echo "File name is empty or chmod isn't a 3-digit number"
    fehler
    exit 1
fi

